name:  WaffleMarm
main:  com.marmalade.wafflemarm.WaffleMarm
version:  1.0
commands:
  hi:
    description: Displays "HI <player>!" 
  jump:
    description: Teleports the player +20 blocks on the y-axis.
 
        