name:  WaffleMarm
main:  com.marmalade.wafflemarm.WaffleMarm
version:  1.0
commands:
  hi:
    description: Displays "HI <player>!" 
  jump:
    description: Teleports the player +20 blocks on the y-axis.
  desert:
    description: Changes all generated chunks to desert biome.
permissions"
    biome.*:
        description: Gives access to all biome commands.
        children:
            biome.desert = op
    biome.desert:
        description: Allows op to change biome to desert.
        default: op         